pipeline {
    agent any
    environment {
        SONARQUBE_URL="20.14.84.78:9000"
        SONAR_TOKEN="sqp_86d0cdb23d7b6e15463630eb6600c25948b4385e"
        DOCKER_USERNAME="jjino"
        DOCKER_PASSWORD="xxxxxxx@29"
    }
    stages {
        stage('DOCKER LOGIN') {
            steps {
              sh ''' 
                echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
              '''
            }
        }
        stage('SONAR SCANNER') {
            steps {
              sh ''' 
                docker run \
                --rm \
                -e SONAR_HOST_URL="http://${SONARQUBE_URL}" \
                -e SONAR_LOGIN="${SONAR_TOKEN}" \
                -v "${PWD}/docker/:/usr/src" \
                sonarsource/sonar-scanner-cli
              '''
            }
        }
        stage('DOCKER IMAGE BUILD') {
            steps {
              sh ''' 
                docker build -t "${DOCKER_USERNAME}/java:apps" -f docker/Dockerfile docker/
              '''
            }
        }
        stage('DOCKER IMAGE PUSH') {
            steps {
              sh ''' 
                docker push "${DOCKER_USERNAME}/java:apps"
              '''
            }
        }
        stage('DOCKER LOGOUT') {
            steps {
              sh ''' 
                docker logout
              '''
            }
        }
        stage('ANSIBLE DEPLOYMENT') {
            steps {
                sh ''' 
                    ansible-playbook ansible/main.yml
                '''
            }
        }
    }
}
