---
- hosts: localhost
  connection: 192.168.0.108
  remote_user: dodo
  tasks:
    - name: Create a java container
      community.docker.docker_container:
        name: java
        image: jjino/java:apps
        state: started
        restart: yes
        ports:
          - "80:8080"
